//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaWeb.ServiceReferenceCliente {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCliente.wsClienteSoap")]
    public interface wsClienteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Agregar(string CodCliente, string Apellidos, string Nombres, string Direccion, string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AgregarAsync(string CodCliente, string Apellidos, string Nombres, string Direccion, string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Eliminar(string CodCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarAsync(string CodCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Actualizar(string CodCliente, string Apellidos, string Nombres, string Direccion, string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ActualizarAsync(string CodCliente, string Apellidos, string Nombres, string Direccion, string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string Categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string Categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Login(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> LoginAsync(string usuario, string contrasena);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsClienteSoapChannel : CapaWeb.ServiceReferenceCliente.wsClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsClienteSoapClient : System.ServiceModel.ClientBase<CapaWeb.ServiceReferenceCliente.wsClienteSoap>, CapaWeb.ServiceReferenceCliente.wsClienteSoap {
        
        public wsClienteSoapClient() {
        }
        
        public wsClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public bool Agregar(string CodCliente, string Apellidos, string Nombres, string Direccion, string Usuario, string Contrasena) {
            return base.Channel.Agregar(CodCliente, Apellidos, Nombres, Direccion, Usuario, Contrasena);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarAsync(string CodCliente, string Apellidos, string Nombres, string Direccion, string Usuario, string Contrasena) {
            return base.Channel.AgregarAsync(CodCliente, Apellidos, Nombres, Direccion, Usuario, Contrasena);
        }
        
        public bool Eliminar(string CodCliente) {
            return base.Channel.Eliminar(CodCliente);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsync(string CodCliente) {
            return base.Channel.EliminarAsync(CodCliente);
        }
        
        public bool Actualizar(string CodCliente, string Apellidos, string Nombres, string Direccion, string Usuario, string Contrasena) {
            return base.Channel.Actualizar(CodCliente, Apellidos, Nombres, Direccion, Usuario, Contrasena);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarAsync(string CodCliente, string Apellidos, string Nombres, string Direccion, string Usuario, string Contrasena) {
            return base.Channel.ActualizarAsync(CodCliente, Apellidos, Nombres, Direccion, Usuario, Contrasena);
        }
        
        public System.Data.DataSet Buscar(string texto, string Categoria) {
            return base.Channel.Buscar(texto, Categoria);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string Categoria) {
            return base.Channel.BuscarAsync(texto, Categoria);
        }
        
        public string[] Login(string usuario, string contrasena) {
            return base.Channel.Login(usuario, contrasena);
        }
        
        public System.Threading.Tasks.Task<string[]> LoginAsync(string usuario, string contrasena) {
            return base.Channel.LoginAsync(usuario, contrasena);
        }
    }
}
