//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaWeb.ServiceReferenceVendedor {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceVendedor.wsVendedorSoap")]
    public interface wsVendedorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Agregar(string CodVendedor, string Apellidos, string Nombres, string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AgregarAsync(string CodVendedor, string Apellidos, string Nombres, string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Actualizar(string CodVendedor, string Apellidos, string Nombres, string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ActualizarAsync(string CodVendedor, string Apellidos, string Nombres, string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Eliminar(string CodVendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarAsync(string CodVendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string Categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string Categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Login(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> LoginAsync(string usuario, string contrasena);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsVendedorSoapChannel : CapaWeb.ServiceReferenceVendedor.wsVendedorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsVendedorSoapClient : System.ServiceModel.ClientBase<CapaWeb.ServiceReferenceVendedor.wsVendedorSoap>, CapaWeb.ServiceReferenceVendedor.wsVendedorSoap {
        
        public wsVendedorSoapClient() {
        }
        
        public wsVendedorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsVendedorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsVendedorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsVendedorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public bool Agregar(string CodVendedor, string Apellidos, string Nombres, string Usuario, string Contrasena) {
            return base.Channel.Agregar(CodVendedor, Apellidos, Nombres, Usuario, Contrasena);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarAsync(string CodVendedor, string Apellidos, string Nombres, string Usuario, string Contrasena) {
            return base.Channel.AgregarAsync(CodVendedor, Apellidos, Nombres, Usuario, Contrasena);
        }
        
        public bool Actualizar(string CodVendedor, string Apellidos, string Nombres, string Usuario, string Contrasena) {
            return base.Channel.Actualizar(CodVendedor, Apellidos, Nombres, Usuario, Contrasena);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarAsync(string CodVendedor, string Apellidos, string Nombres, string Usuario, string Contrasena) {
            return base.Channel.ActualizarAsync(CodVendedor, Apellidos, Nombres, Usuario, Contrasena);
        }
        
        public bool Eliminar(string CodVendedor) {
            return base.Channel.Eliminar(CodVendedor);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsync(string CodVendedor) {
            return base.Channel.EliminarAsync(CodVendedor);
        }
        
        public System.Data.DataSet Buscar(string texto, string Categoria) {
            return base.Channel.Buscar(texto, Categoria);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string Categoria) {
            return base.Channel.BuscarAsync(texto, Categoria);
        }
        
        public string[] Login(string usuario, string contrasena) {
            return base.Channel.Login(usuario, contrasena);
        }
        
        public System.Threading.Tasks.Task<string[]> LoginAsync(string usuario, string contrasena) {
            return base.Channel.LoginAsync(usuario, contrasena);
        }
    }
}
