//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaWeb.ServiceReferenceProducto {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProducto.wsProductoSoap")]
    public interface wsProductoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Agregar(string CodProducto, string Nombre, string UnidadMedida, double Precio, int Stock, string CodCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AgregarAsync(string CodProducto, string Nombre, string UnidadMedida, double Precio, int Stock, string CodCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Eliminar(string CodProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarAsync(string CodProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Actualizar(string CodProducto, string Nombre, string UnidadMedida, double Precio, int Stock, string CodCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ActualizarAsync(string CodProducto, string Nombre, string UnidadMedida, double Precio, int Stock, string CodCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string Categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string Categoria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsProductoSoapChannel : CapaWeb.ServiceReferenceProducto.wsProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsProductoSoapClient : System.ServiceModel.ClientBase<CapaWeb.ServiceReferenceProducto.wsProductoSoap>, CapaWeb.ServiceReferenceProducto.wsProductoSoap {
        
        public wsProductoSoapClient() {
        }
        
        public wsProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public bool Agregar(string CodProducto, string Nombre, string UnidadMedida, double Precio, int Stock, string CodCategoria) {
            return base.Channel.Agregar(CodProducto, Nombre, UnidadMedida, Precio, Stock, CodCategoria);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarAsync(string CodProducto, string Nombre, string UnidadMedida, double Precio, int Stock, string CodCategoria) {
            return base.Channel.AgregarAsync(CodProducto, Nombre, UnidadMedida, Precio, Stock, CodCategoria);
        }
        
        public bool Eliminar(string CodProducto) {
            return base.Channel.Eliminar(CodProducto);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsync(string CodProducto) {
            return base.Channel.EliminarAsync(CodProducto);
        }
        
        public bool Actualizar(string CodProducto, string Nombre, string UnidadMedida, double Precio, int Stock, string CodCategoria) {
            return base.Channel.Actualizar(CodProducto, Nombre, UnidadMedida, Precio, Stock, CodCategoria);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarAsync(string CodProducto, string Nombre, string UnidadMedida, double Precio, int Stock, string CodCategoria) {
            return base.Channel.ActualizarAsync(CodProducto, Nombre, UnidadMedida, Precio, Stock, CodCategoria);
        }
        
        public System.Data.DataSet Buscar(string texto, string Categoria) {
            return base.Channel.Buscar(texto, Categoria);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string Categoria) {
            return base.Channel.BuscarAsync(texto, Categoria);
        }
    }
}
